# Generated by Django 5.1.1 on 2024-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
    ]
