# Generated by Django 5.1.1 on 2024-10-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_update_price', 'Can update product price'), ('can_view_stock', 'Can view stock levels')]},
        ),
    ]
