# docker-compose.yml
services:
  web:
    build:
      context: VTrade_BE  # Adjust this if necessary based on your folder structure
      dockerfile: Dockerfile  # You may omit this if the Dockerfile is named 'Dockerfile'
    ports:
      - "8000:8000"
    volumes:
      - ./VTrade_BE:/code  # Ensure the volume points to the correct project directory
    environment:
      - DB_NAME=${DB_NAME}            # Use variables from .env file
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

